name: 'Super Duper Linter'
description: 'Lints and validates code files in your repository, very helpful for Pull Requests!'
inputs:
  linter:
    description: Name(s) of the linters you wish to run. Runs all by default
    required: false
  customLinterPath:
    description: Specify a relative path within your repository that contains the custom linters. Defaults to "linters". These definitions will OVERRIDE (not merge) definitions of the same name.
    required: false
  path:
    description: Specify a relative path of your repository to lint. Only files in this path will be processed
    required: false
  excludepath:
    description: Explicit file paths to exclude, relative to your root directory. Wildcards are *not* supported
    required: false
  include:
    description: Files patterns to include. Wildcards are supported.
    required: false
  exclude:
    description: Files patterns to exclude. Wildcards are supported.
    required: false
  debug:
    description: Set to True to enable advanced Powershell-level debugging
    required: false
  verbose:
    description: Set to True to enable advanced Powershell-level verbose logging
    required: false
  problemsOnly:
    description: Set to True to only display problems in the test result output
    required: false
  parallel:
    description: Set to the number of linters to run concurrently. By default this is set to the number of logical cores in your system plus 1
    required: false
  all:
    description: Set to True to evaluate all files in the repository, not just those that have changed since the last PR
    required: false
  test:
    description: Set to true to validate the linter operation against defined test cases. This is useful if defining a new custom linter.
    required: false
  severity:
    description: Choose what level of issue severity consistutes a failure of the linter and that it should exit with a non-zero exit status. Options are error, warning, and information. Options are inclusive of their previous choices (e.g. setting information also fails on warnings and errors)
    required: false
outputs:
  result: 
    description: 'A JSON representation of the linter results'

runs:
  using: 'docker'
  image: 'docker://jgrote/superduperlinter:preview'
branding:
  icon: check-circle
  color: green