name: SuperDuperLinter Linter Test
on:
  push:
jobs:
  SuperDuperLinterTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: jgrote
          password: "${{ secrets.DOCKER_HUB_PASSWORD }}"  # you don't need to manually set this secret. GitHub does it on your behalf
          image_name: superduperlinter
          image_tag: cicache
          push_image_and_stages: ${{ github.ref == 'main' }} # Set this to true once when changing the dockerfile to cache the new layers
      - name: Verify Linter Definitions
        uses: ./Tests
        continue-on-error: false
        with:
          test: true
          debug: true
          verbose: true
          customLinterPath: 'Disabled'
      - name: Super Duper Linter - Test Dockerfile
        uses: ./Tests
        continue-on-error: true
        with:
          all: true
          customLinterPath: 'Disabled'